library(RWeka)
library(caret)
train <- read.csv('../Datasets/training-data-10-tuples.csv')
test <- read.csv('../Datasets/test-data-4-tuples.csv')
#train <- read.csv(file.choose())
#test <- read.csv(file.choose())
model <- OneR(buys_computer~., data=train)
prediction <- predict(model, test)
cfMatrix <- confusionMatrix(data=prediction, test$buys_computer)
cfMatrix
